import "./globals.css";
import StructuredData from "@/components/StructuredData";
import { business } from "@/lib/site.config";

export const metadata = {
  metadataBase: new URL(business.url),
  title: {
    default: `${business.name} WA — Premium Roof Repairs, Cleaning & Restoration`,
    template: `%s | ${business.name} WA`,
  },
  description: business.shortDescription,
  keywords: [
    "roof repair Perth",
    "roof cleaning WA",
    "roof restoration Western Australia",
    "roofing contractor Perth",
    "Colorbond roofing",
    "tile roof restoration",
    "terracotta tile roof Perth",
    business.name,
  ],
  authors: [{ name: business.name }],
  creator: business.name,
  publisher: business.name,
  applicationName: business.name,
  category: "Roofing Contractor",
  alternates: { canonical: "/" },
  openGraph: {
    title: `${business.name} WA — Premium Roofing Specialists`,
    description: business.shortDescription,
    url: business.url,
    siteName: business.name,
    locale: "en_AU",
    type: "website",
    // OG/Twitter images are generated by app/opengraph-image.js + twitter-image.js
  },
  twitter: {
    card: "summary_large_image",
    title: `${business.name} WA — Premium Roofing Specialists`,
    description: business.shortDescription,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  icons: {
    icon: [{ url: "/icon.svg", type: "image/svg+xml" }],
    apple: [{ url: "/icon.svg" }],
  },
  formatDetection: { telephone: true, address: true, email: true },
};

export const viewport = {
  themeColor: "#1e1e24",
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en-AU">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        {children}
        <StructuredData />
      </body>
    </html>
  );
}
